# Generated by Django 6.0.5 on 2026-06-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='می\u200cتونی فرمول LaTeX بین علامت $...$ بنویسی، مثل $x^2+1=0$', verbose_name='متن سوال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions/%Y/%m/', verbose_name='تصویر سوال')),
                ('question_type', models.CharField(choices=[('single', 'تک\u200cگزینه\u200cای'), ('multiple', 'چندگزینه\u200cای'), ('truefalse', 'درست / غلط'), ('numeric', 'پاسخ عددی'), ('short', 'پاسخ کوتاه')], default='single', max_length=12, verbose_name='نوع سوال')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], default='medium', max_length=6, verbose_name='سطح سختی')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='بارم (نمره)')),
                ('correct_numeric', models.FloatField(blank=True, null=True, verbose_name='پاسخ عددی صحیح')),
                ('numeric_tolerance', models.FloatField(default=0, help_text='مثلاً 0.01 یعنی جواب تا ±0.01 درست حساب می\u200cشه', verbose_name='خطای مجاز عددی')),
                ('correct_text', models.CharField(blank=True, max_length=255, verbose_name='پاسخ متنی صحیح')),
                ('solution', models.TextField(blank=True, verbose_name='راه\u200cحل / توضیح پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'بانک سوالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='پشتیبانی از LaTeX بین $...$', max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح؟')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 یعنی بدون محدودیت زمانی', verbose_name='مدت زمان (دقیقه)')),
                ('pass_mark', models.PositiveSmallIntegerField(default=50, verbose_name='حد نصاب قبولی (درصد)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='0 یعنی نامحدود', verbose_name='حداکثر دفعات مجاز')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='ترتیب تصادفی سوالات')),
                ('show_solution', models.BooleanField(default=True, verbose_name='نمایش راه\u200cحل بعد از آزمون')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='دوره')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_created', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.lesson', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='in_progress', max_length=12, verbose_name='وضعیت')),
                ('score', models.FloatField(default=0, verbose_name='نمره کسب\u200cشده')),
                ('max_score', models.FloatField(default=0, verbose_name='نمره کل')),
                ('percentage', models.FloatField(default=0, verbose_name='درصد')),
                ('is_passed', models.BooleanField(default=False, verbose_name='قبول؟')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'تلاش آزمون',
                'verbose_name_plural': 'تلاش\u200cهای آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=255, verbose_name='پاسخ متنی')),
                ('is_correct', models.BooleanField(default=False, verbose_name='درست؟')),
                ('points_earned', models.FloatField(default=0, verbose_name='نمره کسب\u200cشده')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in', to='quiz.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='quiz.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='quiz.QuizQuestion', to='quiz.question', verbose_name='سوالات'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام موضوع')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='quiz.topic', verbose_name='موضوع والد')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.topic', verbose_name='موضوع'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='quiz_quizat_student_360a21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'question')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='quiz_questi_topic_i_ad0e50_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='quiz_questi_questio_004b7f_idx'),
        ),
    ]
