# Generated by Django 6.0.5 on 2026-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='slug'),
        ),
    ]
