# Generated by Django 6.0.5 on 2026-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در ��ال انجام'), ('completed', 'تکمیل شده')], default='in_progress', max_length=12, verbose_name='وضعیت'),
        ),
    ]
