# Generated by Django 6.0.5 on 2026-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursemessage',
            new_name='chat_course_course__9c6f58_idx',
            old_name='chat_course_crs_crt_idx',
        ),
    ]
