# Generated by Django 6.0.5 on 2026-06-13 13:50

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'مدیر'), ('teacher', 'استاد'), ('student', 'دانش\u200cآموز'), ('parent', 'والدین')], default='student', max_length=10, verbose_name='نقش')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='شماره تلفن')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='شماره دانش\u200cآموزی')),
                ('entry_year', models.IntegerField(default=1403, verbose_name='سال ورود')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دانش\u200cآموز',
                'verbose_name_plural': 'پروفایل\u200cهای دانش\u200cآموزان',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='تخصص')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدرک تحصیلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل استاد',
                'verbose_name_plural': 'پروفایل\u200cهای اساتید',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='توضیحات کوتاه درباره خودتان', max_length=500, null=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, help_text='تصویر نمایه شما', null=True, upload_to='accounts/avatars/%Y/%m/%d/', verbose_name='تصویر پروفایل')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر پوشش پروفایل', null=True, upload_to='accounts/covers/%Y/%m/%d/', verbose_name='تصویر پوشش')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, help_text='تاریخ تولد شما', null=True, verbose_name='تاریخ تولد')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل سکونت')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='توییتر')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='لینکدین')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='گیت\u200cهاب')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مقالات')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل عمومی',
                'verbose_name_plural': 'پروفایل\u200cهای عمومی',
                'indexes': [models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'), models.Index(fields=['gender'], name='accounts_pr_gender_56b26b_idx'), models.Index(fields=['location'], name='accounts_pr_locatio_4db3cd_idx')],
            },
        ),
    ]
