# Generated by Django 6.0.5 on 2026-05-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'پروفایل دانش\u200cآموز', 'verbose_name_plural': 'پروفایل\u200cهای دانش\u200cآموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'پروفایل استاد', 'verbose_name_plural': 'پروفایل\u200cهای اساتید'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='entry_year',
            field=models.IntegerField(default=1403, verbose_name='سال ورود'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره دانش\u200cآموزی'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('teacher', 'استاد'), ('student', 'دانش\u200cآموز'), ('parent', 'والدین')], default='student', max_length=10, verbose_name='نقش'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='توضیحات کوتاه درباره خودتان', max_length=500, null=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, help_text='تصویر نمایه شما', null=True, upload_to='accounts/avatars/%Y/%m/%d/', verbose_name='تصویر پروفایل')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر پوشش پروفایل', null=True, upload_to='accounts/covers/%Y/%m/%d/', verbose_name='تصویر پوشش')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, help_text='تاریخ تولد شما', null=True, verbose_name='تاریخ تولد')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='محل سکونت')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='توییتر')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='لینکدین')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='گیت\u200cهاب')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مقالات')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل عمومی',
                'verbose_name_plural': 'پروفایل\u200cهای عمومی',
                'indexes': [models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'), models.Index(fields=['gender'], name='accounts_pr_gender_56b26b_idx'), models.Index(fields=['location'], name='accounts_pr_locatio_4db3cd_idx')],
            },
        ),
    ]
