# Generated by Django 6.0.5 on 2026-07-04 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='پرسش')),
                ('answer', models.TextField(blank=True, verbose_name='پاسخ')),
                ('status', models.CharField(choices=[('answered', 'پاسخ داده شد'), ('rejected', 'خارج از محدوده آموزشی'), ('failed', 'خطا در دریافت پاسخ')], default='answered', max_length=10, verbose_name='وضعیت')),
                ('model_used', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='زمان پاسخ (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_questions', to='courses.course', verbose_name='دوره (اختیاری)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرسش هوشمند',
                'verbose_name_plural': 'پرسش\u200cهای هوشمند',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='qa_aiquesti_user_id_6b4cc2_idx')],
            },
        ),
    ]
