# Generated by Django 6.0.5 on 2026-06-13 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام دوره (مثلاً: آموزش جنگو پیشرفته)', max_length=200, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(help_text='آدرس یکتا برای سئو (فیلد خودکار می\u200cشود)', max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='توضیحات کامل دوره', verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(help_text='برای نمایش در کنار عنوان دوره', max_length=300, verbose_name='توضیحات کوتاه')),
                ('thumbnail', models.ImageField(blank=True, help_text='تصویر کوچک برای کارت\u200cهای دوره', null=True, upload_to='courses/thumbnails/%Y/%m/', verbose_name='تصویر بندانگشتی')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر بزرگ برای صفحه اصلی دوره', null=True, upload_to='courses/covers/%Y/%m/', verbose_name='تصویر شاخص')),
                ('level', models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=15, verbose_name='سطح دوره')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('coming_soon', 'به زودی'), ('archived', 'بایگانی شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='قیمت دوره به تومان', max_digits=10, verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='عدد بین 0 تا 100', verbose_name='درصد تخفیف')),
                ('duration_hours', models.PositiveSmallIntegerField(default=0, verbose_name='مدت دوره (ساعت)')),
                ('total_lessons', models.PositiveSmallIntegerField(default=0, help_text='تعداد کل ویدیوهای آموزشی', verbose_name='تعداد جلسات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('enroll_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ثبت\u200cنام')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازها')),
                ('is_full', models.BooleanField(default=False, verbose_name='تکمیل ظرفیت')),
                ('enrollment_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='دسته\u200cبندی')),
                ('students', models.ManyToManyField(blank=True, help_text='از طریق مدل Enrollment مدیریت می\u200cشود', related_name='courses_enrolled', through='Enrollment.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='دانشجویان ثبت\u200cنام شده')),
                ('teachers', models.ManyToManyField(help_text='می\u200cتوانید چند استاد برای این دوره انتخاب کنید', limit_choices_to={'role': 'teacher'}, related_name='courses_teaching', to=settings.AUTH_USER_MODEL, verbose_name='اساتید دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='امتیاز (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازها',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('content_type', models.CharField(choices=[('video', 'ویدیو آموزشی'), ('article', 'متن آموزشی'), ('file', 'فایل آموزشی')], default='video', max_length=20)),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/%Y/%m/')),
                ('article_content', models.TextField(blank=True, verbose_name='متن آموزشی')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='مدت (دقیقه)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to='courses/attachments/%Y/%m/', verbose_name='فایل')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'ضمیمه',
                'verbose_name_plural': 'ضمیمه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نظر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lesson', verbose_name='جلسه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.lessoncomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر جلسه',
                'verbose_name_plural': 'نظرات جلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لایک جلسه',
                'verbose_name_plural': 'لایک\u200cهای جلسات',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تکمیل')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشرفت جلسه',
                'verbose_name_plural': 'پیشرفت جلسات',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='courses_cou_title_6e78a2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'created_at'], name='courses_cou_status_ed6868_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonlike',
            unique_together={('lesson', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('lesson', 'user')},
        ),
    ]
