# Generated by Django 6.0.5 on 2026-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر تعداد دانشجو؛ صفر یعنی نامحدود', verbose_name='ظرفیت دوره'),
        ),
    ]
