# Generated by Django 6.0.5 on 2026-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={},
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='تصویر بزرگ برای صفحه اصلی دوره', null=True, upload_to='courses/covers/%Y/%m/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='تصویر کوچک برای کارت\u200cهای دوره', null=True, upload_to='courses/thumbnails/%Y/%m/', verbose_name='تصویر بندانگشتی'),
        ),
    ]
