# Generated by Django 6.0.5 on 2026-06-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courserating_options_course_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name': 'امتیاز ', 'verbose_name_plural': 'امتیاز ها'},
        ),
    ]
