# Generated by Django 6.0.5 on 2026-06-06 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courserating_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name': 'امتیاز', 'verbose_name_plural': 'امتیازها'},
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='تکمیل ظرفیت'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='درصد تکمیل'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نظر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lesson', verbose_name='جلسه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.lessoncomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر جلسه',
                'verbose_name_plural': 'نظرات جلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لایک جلسه',
                'verbose_name_plural': 'لایک\u200cهای جلسات',
                'unique_together': {('lesson', 'user')},
            },
        ),
    ]
