# Generated by Django 6.0.5 on 2026-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('free', 'رایگان'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='free', max_length=20, verbose_name='وضعیت پرداخت')),
                ('price_paid', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ پرداختی (تومان)')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
